file = open("example.txt","w")
file.write("Hello, this is my first file!\n")
file.close()
file = open("example.txt", "r")
print("\nReading file content:")
print(file.read())
file.close()
file = open("example.txt", "a")
file.write("Adding more content to the file.\n")
file.close()
print("\nData appended successfully!")